teacher_model_dir: "results/hopper-medium-expert-0"

student_model_save_path: ${teacher_model_dir}/student_policy.pth

env: hopper
quality: medium-expert

distill_epochs: 200
distill_batch_size: 1024
distill_lr: 3e-4
eval_episodes: 10
seed: 41

dagger_iters: 25
dagger_rollouts: 50
dagger_epochs: 200

weight_decay: 1e-4

defaults:
  - config
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .